# Generated by Django 5.1.5 on 2025-02-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0002_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
